# Generated by Django 5.2.6 on 2026-05-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_review_user_alter_purchase_user_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='picture',
            field=models.ImageField(null=True, upload_to='developers', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='game',
            name='picture',
            field=models.ImageField(null=True, upload_to='games', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('beta', 'Beta'), ('released', 'Released'), ('early access', 'Early Access'), ('coming soon', 'Coming Soon')], default='coming soon', max_length=50),
        ),
    ]
