# Generated by Django 5.2.6 on 2026-05-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_developer_picture_game_picture_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
