# Generated by Django 5.2.6 on 2026-05-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userprofile_otp_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='developer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='developers', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='games', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
